---
language: node_js
node_js:
- 0.6
before_script:
- curl -o resources/JsTestDriver-1.3.5.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.5.jar'
- java -jar resources/JsTestDriver-1.3.5.jar --config tests/jsTestDriver.conf --port 9876  &
- sleep 3
- phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &
- sleep 3
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:quoridor-online.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git add dev.lmd.js
- yes | git commit dev.lmd.js -m "dev.lmd.js"
- yes | git push heroku master
  
env:
  global:
    secure: ! 'TovnHvsMhcMQ77oaF8lUoMJ6ZD23vzRjDFOunBe30wPxANbov48215pFhMt8

      +iSskX5hGG+tt4OLscQyn3cKiLI8IeUvjU6OfDRdxus3urQAvCgajZv7Fomj

      AVR1KV2z+dBg3liYkZ5Xibt5kJXl/Gx7bqEPI4se9urzAnd4zA4='
