language: node_js
node_js:
- 0.10
before_script:
- npm install -g grunt-cli
#- curl -o resources/JsTestDriver-1.3.5.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.5.jar'
#- java -jar resources/JsTestDriver-1.3.5.jar --config tests/jsTestDriver.conf --port 9876  &
#- sleep 3
#- phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &
#- sleep 3
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:quoridor-online.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
#- heroku plugins:install https://github.com/ddollar/heroku-anvil
#- heroku build -r quoridor-online  -b https://github.com/heroku/heroku-buildpack-nodejs.git
env:
  global:
  - secure: ! 'X8rF/MDHppjeMbb7Qa79W1IIPr/wuQXYwqAa4R7wIdNsEgfVRBMY7tzUBMgt

      Moys64HoO/wh99jjxlKhUpCg/QT0o8e3G5agXGoVN3p4nrBuo1+wYEkUQPhc

      yg5lHC4Yc83oXZRQq5qlZsJ8RXwqhiqdC39vJ3/ijSXfiGlSxTc='